---
- name: Install Docker and Dozzle
  hosts: all
  become: true

  roles:
    - geerlingguy.docker # install docker from extension
    - docker-compose-plugin #detecs OS and installs docker-compose
    - dozzle