---
- name: Install Docker, Dozzle, SearXNG, Caddy, Gitea
  hosts: all
  become: true

  vars:
    docker_install_compose_plugin: true

  roles:
    - geerlingguy.docker
    - docker-compose-plugin
    - dozzle
    - searXNG
    - caddy
    - gitea

