---

- name: Install Docker using geerlingguy.docker role
  hosts: all
  become: true

  roles:
    - geerlingguy.docker



- name: Install Dozzle
  hosts: all
  become: true

  tasks: 
  - name: Install docker-compose-plugin
    apt:
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  - name: Pull dozzle image
    community.docker.docker_image:
      name: amir20/dozzle:latest
      source: pull
      force_source: true

  - name: check dozzle docker volume
    community.docker.docker_volume:
      name: dozzle_data
      state: present

  - name: Remove old Dozzle container if it exists
    community.docker.docker_container:
      name: dozzle
      state: absent
      force: true

  - name: Generate Dozzle users.yml with auth
    community.docker.docker_container:
      name: dozzle-generate-users
      image: amir20/dozzle:latest
      command: >
        generate admin
        --password {{ lookup('env', 'DOZZLE_PASSWORD') }}
        --email {{ lookup('env', 'DOZZLE_EMAIL') }}
        --name {{ lookup('env', 'DOZZLE_USERNAME') }}
      volumes:
        - /opt/dozzle/data:/data
      auto_remove: true
    register: generate_result

    